version: "3"
services:
  crawler:
    build: 
      context: .
    depends_on:
      - redis

  redis:
    image: redis:3
    command: redis-server --appendonly yes
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  redis-commander:
    image: rediscommander/redis-commander
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      REDIS_HOSTS: crawler:redis:6379
    restart: always

volumes:
  redis_data:

